SELECT
/**
Creación: 
18-05-2022. Andrés Del Río. Lista los gestores de proceso e instancia configurados en la ficha de procesos. Nota: Aplica solamente cuando los gestores son grupos de usuarios.

**/
        A.IDACTIVITY ID_PROCESO,
        A.NMACTIVITY NOMBRE_PROCESO,
        PRO.CDTEAMMANAGER CODIGO_GRUPO_GESTOR_PROCESO,
		TP.IDTEAM ID_GRUPO_GESTOR_PROCESO,
		TP.NMTEAM NOMBRE_GRUPO_GESTOR_PROCESO,
		PRO.CDTEAMWFMANAGER CODIGO_GRUPO_GESTOR_INSTANCIA,
		TI.IDTEAM ID_GRUPO_GESTOR_INSTANCIA,
		TI.NMTEAM NOMBRE_GRUPO_GESTOR_INSTANCIA,
		1 AS CANTIDAD
    FROM
        PMACTIVITY A      
    INNER JOIN
        PMPROCESS PRO              
            ON A.CDACTIVITY=PRO.CDPROC 
	LEFT JOIN
		ADTEAM TP
			ON TP.CDTEAM = PRO.CDTEAMMANAGER
	LEFT JOIN
		ADTEAM TI
			ON TI.CDTEAM = PRO.CDTEAMWFMANAGER
	WHERE 
	/** FILTRO POR GRUPO GESTOR DE PROCESO
	TP.IDTEAM = 'SIGSE'
	**/
	/** FILTRO POR ID DE PROCESO
	A.IDACTIVITY LIKE '%ACR.01%'  
	**/
	A.IDACTIVITY LIKE '%ACR.01%'  
